import numpy as np
import multiprocessing
import json
import os
import concurrent.futures
from typing import Union, List, Tuple, Optional

from qiskit import transpile, QuantumCircuit
from qiskit_aer import AerSimulator
from qiskit.circuit.random import random_circuit
from qiskit.providers.backend import BackendV2 as Backend
from qiskit_ibm_runtime import QiskitRuntimeService
from qiskit_ibm_runtime.fake_provider.fake_backend import FakeBackendV2
from qiskit.quantum_info import Statevector


def fix_counts(counts_0: dict, n_qubits: int) -> dict:
    """Fixes the qiskit counts in the standard convention, orders the list, and adds strings with zero counts."""
    
    # Mirror the bit strings to pass in standard convention
    mirrored_counts = {j[::-1]: counts_0[j] for j in counts_0}

    # Sort the results
    dict_items = mirrored_counts.items()
    counts = sorted(dict_items)

    # Add element '00' if it is missing
    if int(counts[0][0], 2) != 0:
        zero = format(0, 'b').zfill(n_qubits)
        counts.insert(0, (zero, 0))

    # Add element '11' if it is missing
    if int(counts[len(counts) - 1][0], 2) != 2**n_qubits - 1:
        uno = format(2**n_qubits - 1, 'b').zfill(n_qubits)
        counts.append((uno, 0))

    # Fill in any missing elements
    for j in range(2**n_qubits - 1):
        if int(counts[j + 1][0], 2) != int(counts[j][0], 2) + 1:
            new = int(counts[j][0], 2) + 1
            new_bin = format(new, 'b').zfill(n_qubits)
            counts.insert(j + 1, (new_bin, 0))
    
    # Convert the list of tuples back into a dictionary
    counts_dict = dict(counts)

    return counts_dict



def perform_parallel_simulation_with_multiprocessing(args: list, simulation: callable, max_workers: int=None):
    """ The .map method allows to execute the function simulation N_process times simultaneously.

    Preserves the order of the given comprehension list. We create a deepcopy of the argument, the simulation currently
    modifies it during execution.
    """

    # Configure pool
    cpu_count = multiprocessing.cpu_count()
    print(f"Our CPU count is {cpu_count}")

    n_processes = max(int(0.8 * cpu_count), 2)
    print(f"Use 80% of the cores, so {n_processes} processes.")

    simulations = len(args)
    chunksize = max(1, int(simulations / n_processes) + (1 if simulations % n_processes > 0 else 0))
    print(f"As we perform {simulations} simulations, we use a chunksize of {chunksize}.")

    # Compute
    p = multiprocessing.Pool(n_processes)
    for time, nqubit in p.imap_unordered(func=simulation, iterable=args, chunksize=chunksize):
        print(f"Simulated {nqubit} qubits in {time} s.", flush=True)

    # Shut down pool
    p.close()
    p.join()


def perform_parallel_simulation(args: list, simulation: callable, max_workers: int=None):
    """ The .map method allows to execute the function simulation N_process times simultaneously.

    Preserves the order of the given comprehension list. We create a deepcopy of the argument, the simulation currently
    modifies it during execution.
    """
    if max_workers is None:
        print("We use max_workers = None, so the default value min(32, os.cpu_count() + 4).")
    else:
        print(f"We use max_workers = {max_workers}.")

    # Execute parallel simulations
    with concurrent.futures.ProcessPoolExecutor(max_workers=max_workers) as executor:
        future_list = [val for val in executor.map(simulation, args)]
        concurrent.futures.wait(future_list)


def mock_perform_parallel_simulation(args: dict, simulation: callable, max_workers: int=None):
    """ This function mocks the parallel simulation.

    It is useful for debugging, because the error messages are displayed. In the real parallel simulation, they are
    muted.
    """
    print("We mock the parallel simulation.")

    for arg in args:
        simulation(arg)


def compute_Hellinger_distance(p_ng: float, p_real: float, nqubits: int) -> float:
    """ Given two distributions as array, returns the Hellinger distance.
    """
    dh_ng = (np.sqrt(p_real)-np.sqrt(p_ng))**2
    h_ng = 0

    for i in range(2**nqubits):
        h_ng = h_ng + dh_ng[i]

    h_ng = (1/np.sqrt(2)) * np.sqrt(h_ng)
    return h_ng  


def create_qc_list(circuit_generator: callable, nqubits_list: list[int], qubits_layout: list[int], backend):
    """ Creates a list of quantum circuit.

    Args:
        circuit_generator (callable): Function which takes the number of qubits and returns a Qiskit circuit.
        nqubits_list (list[int]): List of the qubit numbers for which a quantum circuit should be generated.
        qubits_layout (list[int]): Layout of the qubits in the backend.
        backend: IBM backend.

    Returns:
        A list of transpiled circuits, generated by the Qiskit transpiler. The list items correspond 1:1 to the items in
        the list of qubits.
    """
    print("Warning:")
    print("2) We assume a linear connectivity.")
    sim = AerSimulator()
    result_list = []
    for nqubit in nqubits_list:
        qc2 = transpile(
            circuits=circuit_generator(nqubit),
            backend=backend,
            scheduling_method='asap',
            initial_layout=qubits_layout[0:nqubit],
            seed_transpiler=42,
        )
        result_list.append(qc2)
    return result_list


def load_config(filename: str="") -> dict:
    """ Asks for the config filename in the prompt, loads it and returns it as json file.

    Note: In case you provide a filename as argument, then you can choose to use this filename by providing the empty
    input.
    """
    if filename == "":
        input_filename = input("Which configuration file would you like to use?")
    else:
        input_filename = filename

    config_filename = input_filename if len(input_filename) > 0 else filename
    f = open(f"configuration/{config_filename}")
    config = json.load(f)
    print(f"Loaded configuration {config_filename}.")
    return config


def setup_backend(Token: str = None, device_name: str | FakeBackendV2 = None, crn: str = None, use_fake: bool = False):
    """Takes the backend configuration and returns the configured backend.

    Args:
        Token (str): Token generated with the IBM Quantum Experience account.
        device_name (str | fake_provider): Name of the quantum device. If it is real provide a str data type, and if it is fake provide a fake_provider data type.
        crn (str): Token for the work instance
        use_fake (bool): Decide to use a fake_backend instead of a real one. Default False

    Returns:
        An IBM Quantum provider backend object that provides access to the
        specified quantum device.
    """
    if use_fake:
        backend = device_name
    else:
        service = QiskitRuntimeService(channel='ibm_quantum_platform', token=Token, instance=crn)
        backend = service.backend(device_name)
    return backend


def post_process_split(source_filenames: list, target_filenames: list, split: int):
    """Takes a list of filenames corresponding to the source data. Loads the files as arrays and combines split many
    files into the target files with the given filenames.

    Note:
        This is used as a postprocessing step when we use a split > 1 or when we reduce the shots size and perform
        more experiments.

    Example:
        source_filenames = ["file1.txt", ..., "file100.txt"]
        target_filenames = ["target1.txt", ..., "target10.txt"]
        split = 10
    """
    assert split * len(target_filenames) == len(source_filenames), \
        "Number of provided files and split does not go together."
    assert all((os.path.isfile(f) for f in source_filenames)), "Found invalid filename."
    assert not all((os.path.isfile(f) for f in target_filenames)), "At least one target files already exists."
    assert split > 1, f"Using a split of {split} does not make sense."

    i = 0
    for target_file in target_filenames:
        target_array = np.loadtxt(source_filenames[i])
        for source_file in source_filenames[i+1:i+split]:
            target_array += np.loadtxt(source_file)
        mean_array = target_array / split
        np.savetxt(target_file, mean_array)
        i += split
    return

def create_random_quantum_circuit(n_qubit: int, depth: int, seed_circ: int, measured_qubit: int) -> QuantumCircuit:
    """This function generate a random circuit in Qiskit

    Args:
        n_qubit (int): Number of qubits
        depth (int): Depth of the circuit
        seed_circ (int): Random seed for the random generator
        measured_qubit (int): Number of measured qubits

    Raises:
        ValueError: If there are more measured qubits than of those used in the computation is raised an error

    Returns:
        QuantumCircuit: The random Qiskit quantum circuit
    """


    if measured_qubit > n_qubit:
        raise ValueError(f"More measured qubits {measured_qubit} than of those used in the computation {n_qubit}")

    n_bit = n_qubit
    circ = QuantumCircuit(n_qubit,n_bit)

    circ1 = random_circuit(n_qubit, depth, seed = seed_circ, measure=False)
    circ.compose(circ1, inplace=True)
    circ.barrier()

    for i in range(measured_qubit):
        circ.measure(qubit = i, cbit = i)

    return circ

def transpile_qiskit_circuit(circ : QuantumCircuit, init_layout: list, seed: int, backend: Backend) -> QuantumCircuit:
        """Function to transpile a circuit using the optimal option for this backend.

        Args:
            circ (QuantumCircuit): Quantum circuit to be transpiled
            init_layout (list): initial layout of the qubit
            seed (int): seed for the transpilation
            backend (BackendV2): Qiskit Backend

        Returns:
            QuantumCircuit: Transpiled circuit ready for the run
        """

        t_circ = transpile(
        circuits= circ,
        backend = backend,
        initial_layout=init_layout,
        scheduling_method='asap',
        seed_transpiler=seed
        )

        return t_circ


def pretty_print_data(data):
        """Print human-readable view of preprocessed circuit data.
        
        Args:
            data: list of CircuitInstruction from a circuit.
        """
        for idx, (chunk, flag) in enumerate(data):
            if flag == 0:
                ops_str = " , ".join(
                    f"{op.operation.name}[{', '.join(str(q._index) for q in op.qubits)}]"
                    for op in chunk
                )
                print(f"Chunk {idx}: {ops_str}")
            else:
                op = chunk
                # Handle mid_measurement tuple
                if isinstance(op, tuple) and op[0] == "mid_measurement":
                    meas_op = op[1]
                    q_idx = meas_op["q_idx"]
                    c_idx = meas_op["c_idx"]
                    print(f"Fancy {idx}: mid_measurement qubits={q_idx} clbits={c_idx}")
                    
                elif isinstance(op, tuple) and op[0] == "reset_qubits":
                    meas_op = op[1]
                    q_idx = meas_op["q_idx"]
                    print(f"Fancy {idx}: reset_qubits qubits={q_idx}")
                    
                else:
                    # Normal fancy gate (Instruction)
                    print(
                        f"Fancy {idx}: {op.operation.name} "
                        f"qubits={[q._index for q in op.qubits]} "
                        f"clbits={[c._index for c in op.clbits]}"
                    )

def sv_normal_to_qiskit(sv: Union[np.ndarray, Statevector]) -> np.ndarray:

    """
    Convert a statevector from 'normal' ordering (q0 is MSB)
    into Qiskit ordering (q0 is LSB).

    Normal ordering basis: |q0 q1 ... q(n-1)>
    Qiskit ordering basis: |q(n-1) ... q1 q0>

    Parameters
    ----------
    sv : np.ndarray or Statevector
        Input statevector in normal ordering.

    Returns
    -------
    np.ndarray
        Statevector reordered into Qiskit conventions.
    """
    # Convert Statevector → array
    if isinstance(sv, Statevector):
        arr = sv.data
    else:
        arr = np.asarray(sv)

    # Determine number of qubits
    N = int(np.log2(arr.size))
    if 2**N != arr.size:
        raise ValueError("Input statevector length is not a power of 2.")

    # Reshape into tensor: (2, 2, ..., 2)
    tensor = arr.reshape([2] * N)

    # Reverse axes to flip qubit significance
    tensor_qiskit = np.transpose(tensor, axes=range(N-1, -1, -1))

    # Return flattened statevector
    return tensor_qiskit.reshape(-1)


def sv_qiskit_to_normal(sv: Union[np.ndarray, Statevector]) -> np.ndarray:
    """
    Convert a statevector from Qiskit ordering (q0 is LSB)
    back into 'normal' ordering (q0 is MSB).

    Qiskit ordering basis: |q(n-1) ... q1 q0>
    Normal ordering basis: |q0 q1 ... q(n-1)>

    Parameters
    ----------
    sv : np.ndarray or Statevector
        Input statevector in Qiskit ordering.

    Returns
    -------
    np.ndarray
        Statevector reordered into normal conventions.
    """
    # Convert Statevector → array
    if isinstance(sv, Statevector):
        arr = sv.data
    else:
        arr = np.asarray(sv)

    # Determine number of qubits
    N = int(np.log2(arr.size))
    if 2**N != arr.size:
        raise ValueError("Input statevector length is not a power of 2.")

    # Reshape into tensor: (2, 2, ..., 2)
    tensor = arr.reshape([2] * N)

    # Reverse axes again (inverse operation)
    tensor_normal = np.transpose(tensor, axes=range(N-1, -1, -1))

    # Return flattened vector
    return tensor_normal.reshape(-1)


def extract_qubit_orders(
    transpiled: QuantumCircuit,
    instruction_type: str
) -> List[Tuple[Optional[str], List[int]]]:
    """
    Extract qubit ordering for *either* 'save_statevector' or
    *barriers whose label contains 'save'*.

    Parameters
    ----------
    transpiled : QuantumCircuit
        The transpiled circuit.
    instruction_type : str
        Must be exactly "save_statevector" or "barrier".

    Returns
    -------
    List[Tuple[label, qubit_order]]
        label       : label of the instruction (or None)
        qubit_order : physical qubit indices at that point
    """

    # Strict input validation
    if instruction_type not in ("save_statevector", "barrier"):
        raise ValueError("instruction_type must be either 'save_statevector' or 'barrier'.")

    results: List[Tuple[Optional[str], List[int]]] = []

    for inst, qargs, cargs in transpiled.data:
        
        if instruction_type == "barrier" and inst.name == "barrier":
            if inst.label is not None and 'save' in inst.label:
                label = inst.label
                qubit_order = [transpiled.find_bit(q).index for q in qargs]
                results.append((label, qubit_order))
        
        if instruction_type == "save_statevector" and inst.name == "save_statevector":
            label = inst.label
            qubit_order = [transpiled.find_bit(q).index for q in qargs]
            results.append((label, qubit_order))

    return results


def permute_qiskit_sv_to_logical(
    qiskit_order_sv: np.ndarray,
    qubit_order: List[int]
) -> np.ndarray:
    """
    Reorder a Qiskit-style statevector from *physical qubit order*
    into *logical qubit order*, preserving Qiskit's LSB/MSB convention.

    Qiskit stores statevectors such that qubit 0 is the *least significant bit*.
    If a save_statevector instruction reports physical qubits in a different
    order (e.g., due to layout or transpilation), this function maps the
    statevector back into logical qubit indexing.

    Parameters
    ----------
    qiskit_order_sv : np.ndarray
        Statevector in Qiskit's physical qubit order.

    qubit_order : List[int]
        Mapping: logical_qubit → physical_qubit.
        Example:
            qubit_order = [2, 0, 1]
            means:
                logical q0 = physical q2
                logical q1 = physical q0
                logical q2 = physical q1

    Returns
    -------
    np.ndarray
        logical_qiskit_order_sv :
        The same statevector, but expressed in logical qubit order,
        while retaining Qiskit's least-significant-bit convention.
    """
    qiskit_order_sv = np.asarray(qiskit_order_sv)
    n = len(qubit_order)

    logical_qiskit_order_sv = np.zeros_like(qiskit_order_sv)

    for idx in range(len(qiskit_order_sv)):

        # Extract the physical bitstring from idx
        phys_bits = [(idx >> i) & 1 for i in range(n)]

        # Map physical bits → logical bits
        log_bits = [phys_bits[qubit_order[logical]] for logical in range(n)]

        # Compute index in logical bit order
        new_idx = sum(log_bits[i] << i for i in range(n))

        # Assign amplitude
        logical_qiskit_order_sv[new_idx] = qiskit_order_sv[idx]

    return logical_qiskit_order_sv


def permute_normal_sv_to_logical_normal(
    normal_order_sv: np.ndarray,
    qubit_order: List[int]
) -> np.ndarray:
    """
    Permute a *normal-ordered* statevector (MSB-first) from physical qubit
    order back into logical qubit order, while preserving normal ordering.

    Normal ordering basis:
        |q0 q1 q2 ... q(n-1)>   with q0 = MSB

    The qubit_order array maps:
        logical_qubit -> physical_qubit

    Parameters
    ----------
    normal_order_sv : np.ndarray
        Statevector in physical *normal* ordering (MSB-first).

    qubit_order : List[int]
        Mapping: logical_qubit → physical_qubit index.
        Example: [2, 0, 1] means:
            logical q0 = physical q2
            logical q1 = physical q0
            logical q2 = physical q1

    Returns
    -------
    np.ndarray
        logical_normal_sv :
        Statevector reordered into logical qubit indexing,
        still using MSB-first normal ordering.
    """

    normal_order_sv = np.asarray(normal_order_sv)
    n = len(qubit_order)
    dim = len(normal_order_sv)

    logical_normal_sv = np.zeros_like(normal_order_sv)

    for idx in range(dim):
        # Extract PHYSICAL bits, MSB-first
        # Example: for n=3 → phys_bits = [q0, q1, q2]
        phys_bits = [(idx >> (n-1-i)) & 1 for i in range(n)]

        # Map physical bits → logical bits
        # logical bit i = physical bit qubit_order[i]
        log_bits = [phys_bits[qubit_order[i]] for i in range(n)]

        # Compute new index in normal/MSB-first format
        # |q0 q1 ... q(n-1)>
        new_idx = 0
        for b in log_bits:
            new_idx = (new_idx << 1) | b

        logical_normal_sv[new_idx] = normal_order_sv[idx]

    return logical_normal_sv